# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml




trigger:
  - master
  
stages :
  - stage: Build
    displayName: Build Application
    jobs:
      - job: Backend
        displayName: Build Backend Application
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: './backend/pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'clean package'
              codeCoverageToolOption: JaCoCo
              codeCoverageSourceDirectories: +:com.workshop.*
      
      - job: Frontend
      displayName: Build Frontend Application
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0 
        - script: npm install -d --prefix ./frontend
        - script: npm run tests --prefix ./frontend
        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testRunner: JUnit
            testResultsFiles: '**/TEST-RESULTS.xml'